# Generated by Django 6.1.1 on 2026-09-11 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1, message='Місткість має бути щонайменше %(limit_value)s особа.'), django.core.validators.MaxValueValidator(20, message='Місткість не може перевищувати %(limit_value)s осіб.')], verbose_name='Місткість'),
        ),
    ]
